### ISSUE TITLE
Option to manage the primary group of an user.

### ISSUE THREAD

**Issue by cherva** [deric/puppet-accounts#12]
It will be really nice to have an option to change the primary group of the user.
Now if you try to set a gid to an existing gid the groupmod fails with:
```
Could not set gid on group[john]: Execution of '/usr/sbin/groupmod -g 1696 john' returned 4: groupmod: GID '1696' already exists
```

Update: the normal puppet "user" resource allows you to specify an existing group as primary group.
```puppet
user { "neo":
  ensure     => "present",
  managehome => true,
  gid => 1000 #this is an already existing group
}
```

**Comment by deric** [comment]
You could use the `groups` parameter, right?
```puppet
user { "neo":
  ensure            => "present",
  managehome => true,
  groups            => ['users']
}
```

**Comment by deric** [comment]
I've added a parameter `manage_group`

```puppet
user { "neo":
  manage_group => false,
}
```
which will disable creating a group. Hopefully it will solve your issue.

The naming is not consistent with `managehome`, but I'd like to change that one to `manage_home` is some future release.

**Comment by cherva** [comment]
Hello,
the problem in using groups => ['users'] on neo for example is that this produces
user neo with primary group neo and a secondary group users.
And with the original user resource it produces user neo with primary group users.

**Comment by deric** [comment]
Right, according to [documentation](http://docs.puppetlabs.com/references/latest/type.html#user-attribute-gid) as `gid` we can supply a name, thus you could create a primary group with:

```puppet
user { "neo":
  gid => 'primary-group',
}
```
if we fix the [numerical validation](https://github.com/deric/puppet-accounts/blob/master/manifests/user.pp#L39)
