### ISSUE TITLE
Duplicate declaration: Anchor[accounts::user::groups] is already declared

### ISSUE THREAD

**Issue by jceloria** [deric/puppet-accounts#13]
Using Puppet Enterprise 3.2.4, Any more than one user added in hiera and a error is thrown

common.yaml:
https://gist.github.com/jceloria/8db90da3a47c20d68be1#file-common-yaml

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Anchor[accounts::user::groups] is already declared in file /etc/puppetlabs/puppet/modules/accounts/manifests/user.pp:63; cannot redeclare at /etc/puppetlabs/puppet/modules/accounts/manifests/user.pp:63 on node rmsltlsappp01.netsolve.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

One user however works fine:
https://gist.github.com/jceloria/5563244a67f202f39042#file-common-yaml

**Comment by deric** [comment]
Which version of `puppet-accounts` do you use? I guess it's `v1.1.0`, try upgrading to `v1.1.1` (or latest commit in master - it should be the same).

I've fixed this issue in [5b0b0ad](https://github.com/deric/puppet-accounts/commit/5b0b0adbaaf4909c8bf07d9c0c59d219e0263512).

**Comment by jceloria** [comment]
Thank you, it now works as expected.
