### ISSUE TITLE
Error 400 on SERVER: can't clone TrueClass

### ISSUE THREAD

**Issue by pmbapat** [deric/puppet-accounts#14]
Hit this error with puppet 2.7.26. 

err: Could not retrieve catalog from remote server: Error 400 on SERVER: can't clone TrueClass at /etc/puppet/common/master/modules/accounts/manifests/init.pp:5 on node

**Comment by deric** [comment]
I guess you're missing Hiera as it is not part of Puppet 2.7.x. You can simply install it with
```
gem install hiera
```
Anyway the explicit hiera lookup is not necessary in this case.

**Comment by pmbapat** [comment]
No I'm not. We have a fully working setup with 8-10 puppet masters, hiera etc. 

Problem might be the version of puppet. This works in 3.7.5. But our production is still 2.7.

Below are the lines (with numbers) which cause this.

In init.pp:

  4   $manage_users  = hiera('accounts::manage_users', true),
  5   $manage_groups = hiera('accounts::manage_groups', true),

  9   validate_bool($manage_users)
 10   validate_bool($manage_groups)

I found if we remove these entirely, it runs on puppet 2.7. Somehow puppet and hiera are not able to understand  hiera('accounts::manage_users', true).

**Comment by deric** [comment]
Ok, try using version from master branch. I've tried to fix this in ee29b0de1be48ea60fefea7df518d54df6fe5da2. The automated tests for 2.7 passes, but testing Hiera is tricky and in this case probably not covered enough. It would be great if you would manage to reproduce this in a rspec test.

**Comment by deric** [comment]
Could you please make sure, that you have installed gem `puppet-hiera`, not just `hiera`? I had to revert my patch, but `puppet-hiera` seems to solve the issue on [Puppet 2.7.26](https://travis-ci.org/deric/puppet-accounts/jobs/106468866). If the problem persist, please reopen the issue.
