### ISSUE TITLE
Duplicate declaration: Ssh_authorized_key[undef] is already declared

### ISSUE THREAD

**Issue by jceloria** [deric/puppet-accounts#17]
Using Puppet Enterprise 3.2.7 / puppet-accounts 1.1.2 (commit: c0038e11e75c12b61d41263dad66db2d92e725a5), more than one key added per user in hiera and a error is thrown.

hiera.yaml:
https://gist.github.com/jceloria/790ca984847166c83ffa#file-hiera-yaml

defaults.yaml:
https://gist.github.com/jceloria/6b5c9606418e37999e07#file-defaults-yaml

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Ssh_authorized_key[undef] is already declared in file /etc/puppetlabs/puppet/environments/production/modules/accounts/manifests/user.pp:140; cannot redeclare at /etc/puppetlabs/puppet/environments/production/modules/accounts/manifests/user.pp:140

**Comment by deric** [comment]
Just to clarify, how do you define multiple keys per user? (as an array?) Are you sure you've filled `comment` field for both keys?

**Comment by jceloria** [comment]
My apologies for not being clear, when I only have one key listed per user it works

defaults.yaml:
https://gist.github.com/jceloria/9c522e54bfbc993105e3#file-defaults-yaml

**Comment by jceloria** [comment]
I added the comment to the key and did not receive the same error. I was unaware that the comment was a requirement.

**Comment by deric** [comment]
It is not very intuitive this way, I had to look it up in the code. The fix should be part of `1.1.2`, could you confirm that it works, so that I can tag it? You gave me an idea for new feature: multiple keys support, it shouldn't be hard to implement.

**Comment by jceloria** [comment]
Thank you for the quick response, it works perfectly.
