### ISSUE TITLE
Unsufficinent functionality "Manage ssh keys"

### ISSUE THREAD

**Issue by dene14** [deric/puppet-accounts#20]
you cannot ensure there is no garbage in you authorized_keys currently.

**Comment by deric** [comment]
You're right, I'm planning to add this feature as soon as possible.

**Comment by poikilotherm** [comment]
I think this is related to my PR #27. Maybe you could give some comments?

**Comment by deric** [comment]
Parameter `purge_ssh_keys` was added in `v1.1.3`.
