### ISSUE TITLE
ssh_keys stanza is suboptimal currently :(

### ISSUE THREAD

**Issue by dene14** [deric/puppet-accounts#21]
you have to define username in that stanza explicitly while having ssh_keys in user's configuration stanza.

**Comment by deric** [comment]
I don't understand, could you provide an example?

**Comment by dene14** [comment]
this relates to "ssh_keys", not a "ssh_key", here is my user configuration snippet in JSON:

    "dboulas": {
      "ensure": "present",
      "uid": 1001,
      "gid": 1001,
      "groups": [ ],
      "comment": "Denis Boulas",
      "managehome": true,
      "ssh_keys": {
        "dboulas_key1" : {
          "ensure" : "present",
          "user": "dboulas",
          "type": "ssh-rsa",
          "key": "mykey :)"
        }
      }

**Comment by deric** [comment]
This is already fixed, it's enough to use:
```
  "ssh_keys": {
    "dboulas_key1" : {
      "type": "ssh-rsa",
      "key": "mykey :)"
    }
  }
```
