### ISSUE TITLE
Better uniqness required for ssh_key resource

### ISSUE THREAD

**Issue by dene14** [deric/puppet-accounts#22]
If you have multiple users with 'ssh_keys' stanza defined and each user getting key name "key1", you'll got resource redeclaration...

probably it will be nice to have it automerged with username somehow (for e.g. "${username}_${keyname}")

**Comment by deric** [comment]
Which version do you use? Currently the resource name is composed from `$username_$comment` or `$username_$type`, [see user.pp#L141](https://github.com/deric/puppet-accounts/blob/master/manifests/user.pp#L141).

**Comment by dene14** [comment]
just installed it from puppet forge...
[root@puppet puppet]# puppet module list
/etc/puppet/common_modules
├── deric-accounts (v1.1.2)


This works for "ssh_key", but not for multikeyed version "ssh_keys" since you have plain "create_resources" here

**Comment by deric** [comment]
Was fixed in [v1.1.3](https://github.com/deric/puppet-accounts/releases/tag/v1.1.3), we use [comment or key type](https://github.com/deric/puppet-accounts/commit/6c3871f4fa1567a8b7c16a34c7ddc52ec552da1a)
