### ISSUE TITLE
On user deletion you must ensure there is no "ghost in ZShell"

### ISSUE THREAD

**Issue by dene14** [deric/puppet-accounts#23]
You can't remove user if he's logged in currently. It has security implication by its nature
something like:

```puppet
    if $ensure == "absent" {
      exec { "killproc $name":
        command     => "skill -TERM -u $name; sleep 1; skill -KILL -u $name",
        path        => ["/bin", "/sbin", "/usr/bin", "/usr/sbin"],
        onlyif      => "id $name",
        refreshonly => true
      }
    }
```

before actual {user:} resource invocation with `ensure => absent` flag set should fix the probem

**Comment by deric** [comment]
Right, I think we could add something like this. Why do you use `skill`?

**Comment by dene14** [comment]
feel free to use pkill... nothing special just used to :)

**Comment by deric** [comment]
The `skill` manual says:
> These tools are obsolete and unportable.  The command syntax is poorly defined.  Consider using the > killall, pkill, and pgrep commands instead.

So, I guess `pkill` might be more universal solution.

**Comment by deric** [comment]
There's a parameter `force_removal`, to disable this. By default it is set to `true`.
