### ISSUE TITLE
Creating multiple users using different classifications doesn't work?

### ISSUE THREAD

**Issue by jceloria** [deric/puppet-accounts#24]
I am having trouble creating different users in different environments using hiera classifications.

hiera.yaml:
https://gist.github.com/jceloria/790ca984847166c83ffa#file-hiera-yaml

defaults.yaml:
https://gist.github.com/jceloria/6b5c9606418e37999e07#file-defaults-yaml

hostA.yaml:
https://gist.github.com/jceloria/9af876cabd8682469d9b#file-hosta-yaml

Unless I put all users in the same accounts:users stanza then only the first matching classification in this case (defaults.yaml) and the rest of the user accounts are ignored.

**Comment by zahaim** [comment]
Hello,

If you are still interested I managed to solve this problem by modyfing init.pp in the following way:

```
# Puppet accounts management
#
class accounts(
  $manage_users  = true,
  $manage_groups = true,
#  $users         = {},
#  $groups        = {},
) {

  $users = hiera_hash('accounts::users', {})
  $groups = hiera_hash('accounts::groups', {})
```
(...)
