### ISSUE TITLE
User[root] is already declared

### ISSUE THREAD

**Issue by squesson** [deric/puppet-accounts#29]
```javscript
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: User[root] is already declared; cannot redeclare at /etc/puppet/modules/accounts/manifests/user.pp:114 
on node
```
hieradata:
```ruby
accounts::users:
  myuser:
    ensure: 'present'
  root:
    ensure: 'present'
    manage_group: 'false'
```
seems we cannot manage that user resource type if $name = 'root' . I did not find that root is a reserved word.

**Comment by squesson** [comment]
my mistake, root was really declared elsewhere in another module:
I was calling ensure_resource(account::users, 'root'). I replaced ensure_resource with 
````ruby
if ! defined(accounts::user["$owner"]) {
    accounts::user{ "$owner": ensure => 'present' }
}
````
as discussed here:
https://groups.google.com/forum/#!topic/puppet-users/NFYrD7gdkew

**Comment by deric** [comment]
Ok, normally `ensure_resource` shouldn't cause conflicts with already existing resources.
