### ISSUE TITLE
Parameter options failed on ssh_authorized_key ($ssh_key_defaults)

### ISSUE THREAD

**Issue by adepretis** [deric/puppet-accounts#37]
This commit seems to break the module (when no `options` are passed to the `accounts::user` defined resource): https://github.com/deric/puppet-accounts/commit/bdaadeba4836c6a501c0dfe5373cc2f1dded13c3

> Failed to apply catalog: Parameter options failed on Ssh_authorized_key[xxx]: Option  is not valid. A single option must either be of the form 'option' or 'option="value". Multiple options must be provided as an array

Using `options => undef` or `options => []` instead of `options => ''` fixes it.

**Comment by deric** [comment]
Fixed in af7580d845866203e4d0a4df8e271465054897b0.
