### ISSUE TITLE
$populate_home in v. 1.33

### ISSUE THREAD

**Issue by dfrise** [deric/puppet-accounts#53]
Hi,

First of all: thanks for this awesome module!

The code using `$populate_home` and `$home_directory_contents` has been removed from the
master branch. Is there a reason to that ?

Thanks,
Dominique

**Comment by deric** [comment]
Hey Dominique,

you're welcome :) Thank's for bug report, the feature was poorly documented and without tests. Probably during re-factoring it got lost. There are quite many changes in the master branch, I'll try to draft a release soon.
