### ISSUE TITLE
Invalid resource type accounts::user

### ISSUE THREAD

**Issue by lmbeccaria** [deric/puppet-accounts#55]
I'm getting this error when running "puppet agent t" in the node:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: invalid byte sequence in US-ASCII at /etc/puppet/modules/accounts/manifests/users.pp:13
```

I have other modules installed but the relevant modules look like this:

```
deric-accounts (v1.4.0)
deric-gpasswd (v0.2.3)
puppetlabs-stdlib (v4.6.0)
```

Master:     puppet and puppet-server (v3.6.2) 
Client:       puppet (v3.8.7) 

Thanks

**Comment by deric** [comment]
That's quite strange. There hasn't been any change on that line. It looks like your puppet master has encoding set to `US-ASCII` and `user.pp` is set to UTF-8:
```
$ file -i manifests/users.pp
manifests/users.pp: text/x-c++; charset=us-ascii
$ file -i manifests/user.pp                    
manifests/user.pp: text/plain; charset=utf-8
```
