### ISSUE TITLE
Issue with accounts_group_members() on version 1.5.1

### ISSUE THREAD

**Issue by redno2** [deric/puppet-accounts#65]
After update the module I've got this error:
```
Error: Could not retrieve catalog from remote server: 
Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, accounts_group_members(): 
Wrong number of args, given 3, accepts just 2 at /data/puppetlabs/environments/production/modules/accounts/manifests/init.pp:49:16 on node .....
```

With this hiera :
```yaml
accounts::users:
  john:
    comment: "John Doe"
    groups: ["sudo", "users"]
    shell: "/bin/bash"
    pwhash: "$6$GDH43O5m$FaJsdjUta1wXcITgKekNGUIfrqxYogW"
    ssh_keys:
      'john@doe': # an unique indentifier of a key
        type: "ssh-rsa"
        key: "a valid public ssh key string"
```

Tested on 
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

Does it work on Solaris although it's not write supported ?

Thank you.

**Comment by deric** [comment]
Which version do you use? 

It might work on Solaris, though I haven't test it.

**Comment by redno2** [comment]
puppet version 4.3.2

I need to integrate on Ubuntu and "Solaris and Sles", if you want I can test it and adapt it if necessary, to validate the compatibility for your module.
I have already made an option to avoid modify uid/gid on servers, because is not possible to change some uid/gid on a production server, I'll do a pull request.

**Comment by deric** [comment]
Good, PRs and tests on new platforms are welcomed! Basic integration tests currently runs on CentOS and [Debian](https://travis-ci.org/deric/puppet-accounts/jobs/189199049). It shouldn't be a problem to add Solaris and SLES. Group management currently relies on `gpasswd` which I hope is available in all distributions.

Regarding the error message, how do you install puppet modules? It seems like you're using old version of `accounts_group_members()`, see [the code](https://github.com/deric/puppet-accounts/blob/master/lib/puppet/parser/functions/accounts_group_members.rb#L10), current version would throw this error:
```
"accounts_group_members(): Wrong number of args, given #{args.size}, accepts 2 or 3"
```

**Comment by redno2** [comment]
unfortunately gpasswd doesn't exist on Solaris and the module doesn't change the group in user propriety, we can use usermod instead on Solaris, but need coding.
Not tested on SLES but it has gpasswd.

For accounts_group_members() it was an issue about the cached catalog, I've delete it and it's worked.. Sorry

**Comment by redno2** [comment]
What is the best way to adapt your module on Solaris where is no gpasswd ?

**Comment by deric** [comment]
Ok, I'm glad you've managed to solve it. 

I've opened separated issues (#67, #68) for both OS. I don't have much experience with Solaris, we need to update [commands for adding and removing members](https://github.com/deric/puppet-gpasswd/blob/master/lib/puppet/provider/group/gpasswd.rb#L11). If `usermod` capabilities on Solaris are similar to `gpasswd`, it shouldn't be a problem.
