### ISSUE TITLE
please tag

### ISSUE THREAD

**Issue by soniah** [deric/puppet-accounts#7]
Hi Tomas, thanks for writing puppet-accounts.

Would you mind putting a git tag on your latest work? It would make it easier to work downstream with r10k...

Thanks, Sonia.

**Comment by deric** [comment]
Hey Sonia,

sure. It looks like I forgot to push the latest version to forge :(

**Comment by soniah** [comment]
Thanks :-)

**Comment by deric** [comment]
Tagged as `v1.0.1`. Tag `1.0.0` wasn't created by me, therefore not pushed to forge. Sorry for the mess, let me know if there are any problems.
