### ISSUE TITLE
[blacksmith] Bump version to 1.5.4

### ISSUE THREAD

**Issue by sigv** [deric/puppet-accounts#80]
Since 1.5.3, there have been additional changes - fixes for #69 and #70 as well as #75 have been pushed and progress has been started on #68. Those changes have been tagged as for the 1.6 milestone, but can be very useful for a variety of users so are worthy of being tagged 1.5.4 and pushed to Forge.

As a related side-note, release 1.5.3 is missing a Git tag and was not pushed to Forge.

**Comment by deric** [comment]
I'm sorry, I wanted to fix failing tests before tagging new release.

Regarding the release tag, it's not missing. It just hasn't been released. Blacksmith bumps to next version upon making a release.

**Comment by deric** [comment]
Sorry for the delay v1.5.3 is available at the forge.
