### ISSUE TITLE
1.6 branch - argument must be a string.

### ISSUE THREAD

**Issue by rndmh3ro** [deric/puppet-accounts#82]
Running Puppet 3 on CentOS 7 with the `1.6` branch gives me the following error message:
```
       Notice: Compiled catalog for host in environment development in 26.80 seconds
       Warning: Found multiple default providers for user: usermgr, useradd; using usermgr
       Info: Applying configuration version '1500891341'
       Notice: /Stage[main]/Accounts/Accounts::User[testuser]/User[testuser]/ensure: created
       Notice: /Stage[main]/Accounts/Accounts::Group[mygroup]/Group[mygroup]/ensure: created
       Error: Could not run: argument must be a string.

```
Here's the hiera-config, taken from [here](https://github.com/deric/puppet-accounts/issues/77):
```
accounts::groups:
  mygroup:
    gid: 1141
accounts::users:
  testuser:
    ensure: 'present'
    home: "/home/testuser"
    shell: "/bin/bash"
    uid: 1141
    primary_group: 'mygroup'
    manage_group: true
```

**Comment by deric** [comment]
@rndmh3ro could you post relevant part of `puppet agent -td` output?

**Comment by rndmh3ro** [comment]
The problem only appears if I execute all my puppet modules. If I run `puppet apply --tags=accounts`, the error does not happen.
I guess, the error is connected to this warning:
`Warning: Found multiple default providers for user: usermgr, useradd; using usermgr`

`usermgr` works in a different way than `useradd`. I'll investigate further.

**Comment by rndmh3ro** [comment]
There seems to be a problem on how the module handles passwords.
It's always a problem with the password parameter.
Here are two examples where the module fails with `Error: Could not run: argument must be a string.`

The first one does not user the module at all, however because `usermgr` is used instead of useradd, the error happens.
```
  user { 'nagios':
    ensure            => 'present',
    home              => '/var/spool/nagios',
    shell             => '/sbin/nologin',
    require           => Package['nrpe'],
    password         => '!!',
```

This one using the module fails, too:
```
accounts::users:
  test:
    pwhash: "$6$GDH43O5m$FaJsdjUta1wXcITgKekNGUIfrqxYogW"
```
