### ISSUE TITLE
is there an option control home directory permission for user

### ISSUE THREAD

**Issue by durga1983** [deric/puppet-accounts#86]
Hi My requirement is to create user accounts but  with custom permissions for /home/$user ,  i think by default it is set to 0755 , my requirement is change it to "0750". is there an option like "managehome" for controlling permissions to a specific user home directory while creation.

Thanks

**Comment by deric** [comment]
Looks like duplicate of #85, if I'm not mistaken. Looks like `home_permissions` parameter should resolve it.
