### ISSUE TITLE
Invalid parameter users on Class[Accounts]

### ISSUE THREAD

**Issue by stupied4ever** [deric/puppet-accounts#9]
If I use out of hiera, as described on documentation (https://forge.puppetlabs.com/deric/accounts) I have this error:

`Invalid parameter users on Class[Accounts]`

```ruby
class { '::accounts':
  users => $users, groups => { 'developers' => { }},
}
```

As a work arround, I did:
```ruby
class { 'accounts::groups':
  groups => { 'developers' => { }},
}

class { 'accounts::users':
  users => $users,
}
```
Can you check this?

**Comment by deric** [comment]
Looks like we broke this in feeb6a535f6f1059924d94e33577cfd1c6040ff0 while preferring Hiera approach. I guess we could allow both approaches if we do hash merging in class definition.

**Comment by deric** [comment]
Please test the code from master, if it's ok, I can tag it as a new release.

**Comment by stupied4ever** [comment]
@deric Sorry for the long time without answer, I will test this as soon as possible, and I give you a feed back.
