### ISSUE TITLE
New release timeline?

### ISSUE THREAD

**Issue by tnail** [deric/puppet-accounts#96]
Are there plans for a new release (possibly in the 2.0 branch)? Also, is 2.0 stable enough for use (I see the documentation references to it)?

Thanks,

-=Tom Nail

**Comment by deric** [comment]
I'm sorry about that :disappointed: It was supposed to be released long time ago. It is stable enough with a [massive changelog](https://github.com/deric/puppet-accounts/compare/v1.5.3...master). I was about to update documentation and release it, but some work got had to be done.

**Comment by deric** [comment]
@tnail [v2.0.0](https://github.com/deric/puppet-accounts/releases/tag/v2.0.0) has been released.
