### ISSUE TITLE
authorized keys error in 2.0.x

### ISSUE THREAD

**Issue by tnail** [deric/puppet-accounts#97]
I'm loading account::user information using version 2.0.0-beta1 with ssh-keys defined in the hiera data and am running into this error:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, can't convert String into Hash (file: /etc/puppetlabs/code/environments/DEV/modules/accounts/manifests/authorized_keys.pp, line: 76, column: 5) (file: /etc/puppetlabs/code/environments/DEV/modules/accounts/manifests/user.pp, line: 250) on node`

I'm able to list the keys data using 'puppet lookup' and it looks like it's returning a hash, so I'm not sure where to go from here:

`puppet lookup --merge deep --debug --explain accounts::users --node <node_name> --environment DEV`

(after a lot of other debug information, one of the user hashes returns....)

`    Module data provider for module "accounts" not found
    Merged result: {
      "root" => {
        "pwhash" => "noyou'renotgettingmyrootpasswpordhash...",
        "home" => "/root"
      },
      "su-admin" => {
        "comment" => "Admin",
        "uid" => "300000",
        "groups" => [
          "admin"
        ],
        "ssh_keys" => {
          "name" => "admin@jumphost",
          "type" => "ssh-rsa",
          "key" => "AorthisSSHkeyeitherPM="
        }
      },`

Puppet is version 5.5.12 (open source)

**Comment by tnail** [comment]
Okay, this was me being stupid in my ssh_keys definitions... Apologies to all who took a look at it. Apparently, the yaml syntax for the ssh_keys hash needs a 'keyname' tag in the definition, like:

```
ssh_keys:
    'keyname':
       name: "somename"
       type: "ssh-rsa"
       key: "AAAAbbbb..... etc."
```

Otherwise, the authorized_keys.pp doesn't have anything to hang the hash value on and thinks the remainder of the data is just a string. Or so I theorize.

**Comment by deric** [comment]
Yes, the `keyname` is resource title for [`ssh_authorized_key`] (https://puppet.com/docs/puppet/5.5/types/ssh_authorized_key.html#ssh_authorized_key-attributes). It should be an unique identifier. Let me know if the documentation could be improved.

**Comment by tnail** [comment]
It's documented well enough in the comments in `authorized_keys.pp` and [`ssh_authorized_key`] I just need to learn to read, apparently. =/ The error message is a bit cryptic, but I eventually figured out where to look.
